### ISSUE TITLE
Issue with worng expiration date field

### ISSUE THREAD

**Issue by iAhmadZain** [rdap-org/client.rdap.org#3]
Hi, we do have issue that some domains reported worng expiration dates from that recorded in the RDAP and when compared it to Whois or Domain-tools they reflected the correct values.

**Comment by gbxyz** [comment]
Hi there, is the RDAP server returning the correct expiration date (that the web client is then displaying incorrectly?

Could you please provide some example domains where you see this?

**Comment by iAhmadZain** [comment]
Hi @gbxyz thanks for your reply,
client.rdap.org and the API returning wrong values. examples can not be provided due to privacy however i am attaching the screenshots for same domain.
RDAP
![CleanShot 2024-11-11 at 14 53 05](https://github.com/user-attachments/assets/bd24f365-92ba-4ed1-8e6d-0b7cef0ed0a7)
WhoIS 
![CleanShot 2024-11-11 at 14 54 36](https://github.com/user-attachments/assets/0df98189-d46d-4bd6-81e1-285875ac2919)

**Comment by gbxyz** [comment]
Without knowing the specific domain names I cannot verify the issue or attempt to resolve it.

If you would rather not disclose the specific domains here you can email me at gavin.brown@fastmail.uk.

**Comment by gbxyz** [comment]
Thanks for sharing the domain name privately.

The issue here is that the _registrar_ reports a different expiry date to the _registry_. This is true for both port-43 WHOIS and RDAP. You see different dates because your whois client is using the data from one server and the RDAP client is showing data from the other.

```
Expiration date (via port-43 whois):
Registry:  2025-11-06T21:31:20Z
Registrar: 2024-11-06T21:31:20Z

Expiration date (via RDAP):
Registry:  2025-11-06T21:31:20Z
Registrar: 2024-11-06T21:31:20-07:00
```

So this not a bug in the RDAP web client: the registrar is not in compliance with the RDAP specs which say that the two dates should be consistent.

Report them to ICANN compliance!

**Comment by iAhmadZain** [comment]
thanks @gbxyz
